# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'authorization.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Authorization")
        Dialog.setEnabled(True)
        Dialog.resize(581, 318)
        Dialog.setStyleSheet("background-color: rgb(43, 43, 43);")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 583, 321))
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setAutoFillBackground(True)
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.091, y1:0.863636, x2:1, y2:0.0170455, stop:0.0909091 rgba(0, 32, 104, 255), stop:0.988636 rgba(246, 138, 198, 255));")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(200, 90, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("color: #fff;\n"
"text-align: center;\n"
"background-color: rgb(204, 120, 182);\n"
"border: 4px solid white;\n"
"border-radius: 10%;")
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setGeometry(QtCore.QRect(170, 150, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("text-align: center;\n"
"border: 4px solid white;\n"
"background-color: rgb(204, 120, 182);\n"
"border-radius: 10%;\n"
"color: #fff;")
        self.lineEdit.setText("")
        self.lineEdit.setMaxLength(20)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(210, 230, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: #fff;\n"
"text-align: center;\n"
"background-color: rgb(204, 120, 182);\n"
"border: 4px solid white;\n"
"border-radius: 10%;")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Authorization", "Authorization"))
        self.label.setText(_translate("Authorization", "Choose nickname"))
        self.lineEdit.setPlaceholderText(_translate("Authorization", "Введите никнейм"))
        self.pushButton.setText(_translate("Authorization", "OK"))
