# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chatWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Tenzor messanger with love")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.091, y1:0.863636, x2:1, y2:0.0170455, stop:0.0909091 rgba(0, 32, 104, 255), stop:0.988636 rgba(246, 138, 198, 255));")
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 530, 661, 51))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 87 10pt \"Arial Black\";\n"
"color: #000;\n"
"border: 4px solid white;\n"
"border-radius: 10%;")
        self.lineEdit.setText("")
        self.lineEdit.setReadOnly(False)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(690, 530, 101, 51))
        self.pushButton.setStyleSheet("color: #000;\n"
"border: 4px solid white;\n"
"font: 75 14pt \"Tahoma\";\n"
"border-radius: 10%;\n"
"background-color: rgb(170, 255, 127);")
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(23, 30, 641, 481))
        self.textEdit.setStyleSheet("color: #000;\n"
"border: 4px solid white;\n"
"border-radius: 10%;\n"
"background-color: rgb(255, 255, 255);")
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Tenzor messanger with love", "Tenzor messanger with love"))
        self.pushButton.setText(_translate("Tenzor messanger with love", "SEND"))
        self.lineEdit.setPlaceholderText(_translate("Tenzor messanger with love", "Введите сообщение"))
        self.textEdit.setHtml(_translate("Tenzor messanger with love", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
